# Copy to system clipboard
[[mgr.prepend_keymap]]
on  = "y"
run = [ 'shell -- for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list', "yank" ]
desc = "Yank file to system clipboard"

# Compress
[[mgr.prepend_keymap]]
on = [ "c", "a" ]
run = "plugin ouch"
desc = "Compress with ouch"

# Dragon
[[mgr.prepend_keymap]]
on = [ "<C-g>" ]
run = '''
    shell 'ripdrag "$@" -x 2>/dev/null &' --confirm
'''
desc = "Drag and drop"

# Mount
[[mgr.prepend_keymap]]
on = "M"
run = "plugin mount"

# Relative-motions plugin
[[mgr.prepend_keymap]]
on = [ "m" ]
run = "plugin relative-motions"
desc = "Trigger a new relative motion"

# Yamb plugin (Yet another bookmarks)
[[mgr.prepend_keymap]]
on = [ "u", "a" ]
run = "plugin yamb save"
desc = "Add bookmark"

[[mgr.prepend_keymap]]
on = [ "u", "g" ]
run = "plugin yamb jump_by_key"
desc = "Jump bookmark by key"

[[mgr.prepend_keymap]]
on = [ "u", "G" ]
run = "plugin yamb jump_by_fzf"
desc = "Jump bookmark by fzf"

[[mgr.prepend_keymap]]
on = [ "u", "d" ]
run = "plugin yamb delete_by_key"
desc = "Delete bookmark by key"

[[mgr.prepend_keymap]]
on = [ "u", "D" ]
run = "plugin yamb delete_by_fzf"
desc = "Delete bookmark by fzf"

[[mgr.prepend_keymap]]
on = [ "u", "A" ]
run = "plugin yamb delete_all"
desc = "Delete all bookmarks"

[[mgr.prepend_keymap]]
on = [ "u", "r" ]
run = "plugin yamb rename_by_key"
desc = "Rename bookmark by key"

[[mgr.prepend_keymap]]
on = [ "u", "R" ]
run = "plugin yamb rename_by_fzf"
desc = "Rename bookmark by fzf"

# Smart enter
[[mgr.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

# Close by one escape
[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"
