# Gestures conf
# Gestures implemented via libinput-gestures (see libinput-gestures.conf)

gestures {
    workspace_swipe = on
    workspace_swipe_cancel_ratio = 0.15
    workspace_swipe_distance = 500
    workspace_swipe_forever = true
    workspace_swipe_use_r = true
    workspace_swipe_create_new = true
}
