# My window rules

windowrule = opacity 0.9, initialClass:code

windowrule = float, initialTitle:Open(.*) 
windowrule = center, initialTitle:Open(.*)
windowrule = opacity 0.9, initialTitle:Open(.*)
# windowrule = size 80% 80%, initialTitle:Open(.*)

windowrule = float, initialTitle:^(((.*)Export(.*))|((.*)Save(.*)))$
windowrule = opacity 0.9, initialTitle:^(((.*)Export(.*))|((.*)Save(.*)))$
windowrule = center, initialTitle:^(((.*)Export(.*))|((.*)Save(.*)))$
windowrule = size 80% 80%, initialTitle:^(((.*)Export(.*))|((.*)Save(.*)))$

windowrule = float, initialClass:hyprland-share-picker
windowrule = opacity 0.8, initialClass:hyprland-share-picker
windowrule = center, initialClass:hyprland-share-picker
windowrule = size 80% 80%, initialClass:hyprland-share-picker

windowrule = float, initialClass:qView
windowrule = center, initialClass:qView
windowrule = size 80% 80%, initialClass:qView

windowrule = size <30% <15%, initialClass:^(.*)(Thunar|thunar)(.*)$, title:.*Rename.*
windowrule = float, initialClass:^(.*)(Thunar|thunar)$
windowrule = opacity 0.8, initialClass:^(Thunar|thunar)$
windowrule = size 85% 85%, initialClass:^(.*)(Thunar|thunar)$
windowrule = center, initialClass:^(.*)(Thunar|thunar)$

windowrule = float, initialClass:(.*)(telegram)(.*)
windowrule = opacity 0.85, initialClass:(.*)(telegram)(.*)
windowrule = size 95% 90%, initialClass:(.*)(telegram)(.*)
windowrule = center, initialClass:(.*)(telegram)(.*)
windowrule = opacity 1, class:org.telegram.desktop, title:Media viewer

windowrule = opacity 0.9, initialClass:(.*)(obsidian)(.*)

windowrule = float, initialClass:(.*)(qalculate-gtk)(.*)
windowrule = opacity 0.8, initialClass:(.*)(qalculate-gtk)(.*)
windowrule = center, initialClass:(.*)(qalculate-gtk)(.*)
windowrule = size 70% 70%, initialClass:(.*)(qalculate-gtk)(.*)

windowrule = float, initialClass:(.*)(qView)(.*)
windowrule = center, initialClass:(.*)(qView)(.*)
windowrule = size 80% 80%, initialClass:(.*)(qView)(.*)

windowrule = opacity 0.9, initialClass:(.*)(vesktop)(.*)

windowrule = opacity 0.9, initialTitle:^(.*)(Spotify)(.*)$
windowrule = workspace special:music, initialTitle:^(.*)(Spotify)(.*)$ 

# "Smart" gaps
windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
windowrule = rounding 0, floating:0, onworkspace:w[tv1]
windowrule = bordersize 0, floating:0, onworkspace:f[1]
windowrule = rounding 0, floating:0, onworkspace:f[1]
